/** IPC channel names shared between main, preload and renderer. */
export const IPC = {
  // invoke (renderer -> main)
  getProjects: 'projects:get',
  scan: 'projects:scan',
  deleteNodeModules: 'projects:delete',
  deleteManyNodeModules: 'projects:delete-many',
  revealInFinder: 'projects:reveal',
  openProject: 'projects:open',
  getSettings: 'settings:get',
  setSetting: 'settings:set',
  openLauncher: 'window:open-launcher',
  closeWindow: 'window:close-self',
  setWindowHeight: 'window:set-height',
  quitApp: 'app:quit',
  trackEvent: 'analytics:track',
  uninstall: 'app:uninstall',
  getLastScanTime: 'scan:last-time',
  getPnpmStore: 'pnpm-store:get',
  prunePnpmStore: 'pnpm-store:prune',
  getPackages: 'packages:get',
  computePackages: 'packages:compute',
  openExternal: 'shell:open-external',
  pickPath: 'dialog:pick-path',
  getLicense: 'license:get',
  activateLicense: 'license:activate',
  copyShareCard: 'share:copy-card',
  listVolumes: 'volumes:list',
  getLiveProjects: 'projects:live',
  // events (main -> renderer)
  onScanProgress: 'scan:progress',
  onProjectsChanged: 'projects:changed',
  onSettingsChanged: 'settings:changed',
  onLicenseChanged: 'license:changed',
} as const
